run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  staticcheck:
    checks:
      - all

issues:
  exclude-dirs:
    - vendor
  max-issues-per-linter: 50
  max-same-issues: 5
